// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/sub/sub.proto

package go_micro_srv_sub

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Sub service

type SubService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Sub_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Sub_PingPongService, error)
}

type subService struct {
	c    client.Client
	name string
}

func NewSubService(name string, c client.Client) SubService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.sub"
	}
	return &subService{
		c:    c,
		name: name,
	}
}

func (c *subService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Sub.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Sub_StreamService, error) {
	req := c.c.NewRequest(c.name, "Sub.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &subServiceStream{stream}, nil
}

type Sub_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type subServiceStream struct {
	stream client.Stream
}

func (x *subServiceStream) Close() error {
	return x.stream.Close()
}

func (x *subServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *subServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *subServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *subService) PingPong(ctx context.Context, opts ...client.CallOption) (Sub_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Sub.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &subServicePingPong{stream}, nil
}

type Sub_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type subServicePingPong struct {
	stream client.Stream
}

func (x *subServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *subServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *subServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *subServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *subServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Sub service

type SubHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Sub_StreamStream) error
	PingPong(context.Context, Sub_PingPongStream) error
}

func RegisterSubHandler(s server.Server, hdlr SubHandler, opts ...server.HandlerOption) error {
	type sub interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Sub struct {
		sub
	}
	h := &subHandler{hdlr}
	return s.Handle(s.NewHandler(&Sub{h}, opts...))
}

type subHandler struct {
	SubHandler
}

func (h *subHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.SubHandler.Call(ctx, in, out)
}

func (h *subHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.SubHandler.Stream(ctx, m, &subStreamStream{stream})
}

type Sub_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type subStreamStream struct {
	stream server.Stream
}

func (x *subStreamStream) Close() error {
	return x.stream.Close()
}

func (x *subStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *subStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *subStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *subHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.SubHandler.PingPong(ctx, &subPingPongStream{stream})
}

type Sub_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type subPingPongStream struct {
	stream server.Stream
}

func (x *subPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *subPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *subPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *subPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *subPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
